CREATE TABLE NOTICE (
	ID NUMBER,
	TITLE	NVARCHAR2(100),
	WRITER_ID	NVARCHAR2(50),
	CONTENT	CLOB,
	REGDATE TIMESTAMP DEFAULT SYSDATE,
	HIT	NUMBER,
	FILES	NVARCHAR2(1000),
	PUB NUMBER DEFAULT 0
);

CREATE SEQUENCE NOTICE_SEQ 
INCREMENT BY 1 
START WITH 1
MINVALUE 1
MAXVALUE 1000
NOCYCLE;

DROP SEQUENCE NOTICE_SEQ;
DROP TABLE NOTICE;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM NOTICE;
SELECT NOTICE_SEQ.NEXTVAL FROM DUAL;
SELECT NOTICE_SEQ.CURRVAL FROM DUAL;


INSERT INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, HIT)
values(1, 'aaa', 'gun5032', '안녕하세요케케케', 111);
INSERT INTO NOTICE(ID, TITLE, WRITER_ID, CONTENT, HIT)
values(2, 'bbb', 'gunbbb', '안녕bb', 222);
INSERT INTO NOTICE values(1, 'JDBC란 무엇인가?', 'newlec', 'aaa', SYSDATE, 0, '');
INSERT INTO NOTICE values(2, 'JAVA란 무엇인가?', '남궁성', 'bbbb', SYSDATE, 1, '');
INSERT INTO NOTICE values(3, 'JS 무엇인가?', 'ECON', 'cccc', SYSDATE, 1, '');

INSERT INTO NOTICE (TITLE, WRITER_ID, CONTENT, FILES)
			VALUES('TEST', 'newlec', 'test content', '');

UPDATE NOTICE
   SET HIT = 11
 WHERE ID = 3;

SELECT * FROM NOTICE;

DROP TABLE NOTICE;


CREATE TABLE COMMENT1 (
	ID	NUMBER,
	CONTENT		NVARCHAR2(2000),
	REGDATE		TIMESTAMP,
	WRITER_ID	NVARCHAR2(50),
	NOTICE_ID	NUMBER
);

CREATE TABLE ROLE(
	ID	VARCHAR2(50),
	DISCRIPTION NVARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE (
	MEMBER_ID	NVARCHAR2(50),
	ROLE_ID		VARCHAR2(50)
);

CREATE TABLE MEMBER (
	ID NVARCHAR2(50),
	PWD NVARCHAR2(50),
	NAME NVARCHAR2(50),
	GENDER	NCHAR(2),
	BIRTHDAY CHAR(10),
	PHONE CHAR(13),
	REGDATE DATE,
	EMAIL VARCHAR2(200)
);

SELECT * FROM NOTICE;
SELECT * FROM COMMENT1;
SELECT * FROM MEMBER;
DROP TABLE NOTICE;
